### PR TITLE
Add normalization script

### PR DESCRIPTION
**Pull request by graphemecluster**
`jyut6ping3_max.schema.yaml` should be moved to `rime-cantonese-schemes`.

Check well before merging.

### CODE REVIEW

**Comment by tanxpyox** [comment]
Have you time-tested the new versions? I fear the abundance of lookahead's and lookbehind's will incur significant memory and time cost (because they basically break the greedy logic).

**Comment by graphemecluster** [comment]
I forget to think about it at all, actually, as I think that the time and the memory cost should not be affected too much, in the case of a good engine.
Of course, it will be great if the RIME engine could change `/(?<=before)content(?=after)/` to `/(before)content(after)/$1replacement$2/` internally.

As I cannot promise everything is working correctly, should I make this PR a draft first after all?

**Comment by tanxpyox** [comment]
> As I cannot promise everything is working correctly, should I make this PR a draft first after all?

hmm I think that's perhaps the best we can do now - at least that would give us ample time for checking later

**Comment by graphemecluster** [comment]
I totally forget this branch, this PR and all my previous efforts on the (old) normalization script. 😅 Let's close it for the time being.

**Pull request closed without merging**
